[features]
idl-build = ["anchor-lang/idl-build"]
seeds = false
skip-lint = false
[programs.localnet]
rust_anchor = "BF1Q7hLntSidgYjCMzG298QpRbBb5daA672W7mNiWFVf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/miraku/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"