[package]
name = "rust-solana"
version = "0.1.0"
edition = "2024"
description = "A Solana program written in Rust"

[dependencies]
solana-program = "=2.0.3"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []